### PR TITLE
Update gatsby-image-plugin to stable release

### PR DESCRIPTION
**Pull request by jacobarriola**
### Description
This PR updates the `gatsby-image-plugin` from the beta version to a stable release. It also updates the two required dependencies: `gatsby-plugin-sharp` `gatsby-transformer-sharp`.

### What I fixed
* An incorrect `layout` type was passed to the GraphiQL screenshots for the homepage. `FLUID` doesn't exist. Instead, I passed in `CONSTRAINED`.
* `maxWidth` is deprecated. Using `width` instead.

### What I added
* ⚡️AVIF support to image queries (home page)
* 🙌 Zeek Interactive logo to WhoIsUsing component

### Any relevant tickets?
#9 #12

### CODE REVIEW

**Comment by jacobarriola** [comment]
@jasonbahl let me know if there any changes you'd like to see. I don't see any examples of tests, so let me know if there are some tests you'd like me to write.

Thanks!

**Comment by jasonbahl** [comment]
@jacobarriola ya, I don't have tests for this codebase yet. 🙈

**Comment by jasonbahl** [comment]
@jacobarriola when Gatsby Cloud is building this, it outputs the following: 

Screen Shot 2021-04-01 at 8 42 05 AM
Screen Shot 2021-04-01 at 8 42 10 AM

**Comment by jasonbahl** [comment]
^ That said, the build succeeded, so we can work on those issues later. 🤷‍♂️ 

Site is now deployed with these changes 👏

**Pull request merged**
